spring:
  application:
    name: user-canter
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/person
server:
  port: 8080

